name: tasra
favicon: null
layout_spectrum: 0.77936
typography_spectrum: 0.42216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a19f92'
    - '#988274'
    - '#41372d'
    - '#b7b4ab'
    - '#6c5044'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.75
purpose:
  - name: stars
    item: null
    url: null
