name: tasra
favicon: null
layout_spectrum: 1
typography_spectrum: 0.97554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfccbc'
    - '#5a5552'
    - '#b89a80'
    - '#7e756d'
    - '#a28876'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose:
  - name: stars
    item: null
    url: null
