name: tasra
favicon: null
layout_spectrum: 0.77936
typography_spectrum: 0.42216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4d5d7'
    - '#4e4945'
    - '#8b847e'
    - '#2c2723'
    - '#080705'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.75
purpose:
  - name: stars
    item: null
    url: null
