name: tasra
favicon: null
layout_spectrum: 0.77936
typography_spectrum: 0.97554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e2de'
    - '#049ea4'
    - '#004d63'
    - '#c0b9ab'
    - '#816c53'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: stars
    item: null
    url: null
